// Icon generator.
//
// One path definition, five outputs: the SVG source, the Android adaptive-icon
// foreground and its monochrome twin, the splash drawable, the legacy mipmap
// PNGs (API 23-25 has no adaptive icons) and the PWA icons. Hand-maintaining
// those separately is how an app ends up with a launcher icon that does not
// match its splash, so they are all derived here.
//
//   node scripts/gen-icons.mjs
//
// The mark is an anvil: Tempa means "to forge", and every other app in the
// category is a dumbbell. It has to survive being 48px on a busy home screen,
// so it is one silhouette with no interior detail.

import { mkdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const RES = join(ROOT, 'android/app/src/main/res')

// Brand colours — keep in step with res/values/colors.xml and --seed-d/--surf
// in src/index.css.
const SURFACE = '#151312'
const PRIMARY = '#FF9A4D'
const PRIMARY_DEEP = '#E8630F'

// The anvil, drawn on the 108-unit grid Android adaptive icons use. Its own
// bounds are x 22..87, y 34..80, centred on (54.5, 57) — the GROUP transform
// below is what places and scales it, so this string is never re-tuned.
//
// The horn is blunt and stops short of the slab's full height. A long straight
// taper to a point — the first attempt — read as an arrow pointing right at
// launcher size, which is a worse failure than being slightly less anvil-like:
// an arrow is a UI glyph and the eye files it as one.
const ANVIL = 'M22 34 H68 L83 40 Q87 43 83 46 L68 52 H58 L62 68 H70 Q74 68 74 72 V76 Q74 80 70 80 ' +
              'H28 Q24 80 24 76 V72 Q24 68 28 68 H36 L40 52 H22 Z'
const ART_CX = 54.5, ART_CY = 57

// Adaptive icons are masked to arbitrary shapes; only the central 66dp circle of
// the 108dp canvas is guaranteed to survive. At 0.72 the anvil's furthest corner
// sits 29.6 units from centre, inside that 33-unit radius with room to spare.
const ADAPTIVE_SCALE = 0.72
// A full-bleed icon has no mask to fear, so the mark can breathe wider.
const FLAT_SCALE = 0.94

const svgGroup = (scale, fill) => {
  const tx = 54 - ART_CX, ty = 54 - ART_CY
  return `<g transform="translate(${tx} ${ty}) translate(${ART_CX} ${ART_CY}) ` +
         `scale(${scale}) translate(${-ART_CX} ${-ART_CY})" fill="${fill}">` +
         `<path d="${ANVIL}"/></g>`
}

const vectorGroup = (scale, fill) => `    <group
        android:pivotX="${ART_CX}"
        android:pivotY="${ART_CY}"
        android:scaleX="${scale}"
        android:scaleY="${scale}"
        android:translateX="${54 - ART_CX}"
        android:translateY="${54 - ART_CY}">
        <path android:fillColor="${fill}" android:pathData="${ANVIL}" />
    </group>`

const vectorFile = (body, note) => `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/gen-icons.mjs — do not edit by hand.
     ${note} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${body}
</vector>
`

// ------------------------------------------------------------------ SVG ----
// The full-bleed source, used for the PNGs and as the store icon master.
const flatSvg = (size, bg = SURFACE) => `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 108 108">
  <defs>
    <linearGradient id="ember" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="${PRIMARY}"/>
      <stop offset="1" stop-color="${PRIMARY_DEEP}"/>
    </linearGradient>
  </defs>
  <rect width="108" height="108" fill="${bg}"/>
  ${svgGroup(FLAT_SCALE, 'url(#ember)')}
</svg>`

// Maskable variants keep the mark inside the safe circle, so a launcher that
// crops to a circle never clips the horn.
const maskableSvg = (size, bg = SURFACE) => `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 108 108">
  <rect width="108" height="108" fill="${bg}"/>
  ${svgGroup(ADAPTIVE_SCALE, PRIMARY)}
</svg>`

// ------------------------------------------------------------- densities ---
// Legacy launcher icons. API 26+ uses the adaptive icon instead, but minSdk is
// 23 and Indonesia still has a long tail of those devices.
const MIPMAP = { ldpi: 36, mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 }

async function main() {
  // adaptive icon pieces (pure XML — crisp at every density, no PNG needed)
  writeFileSync(join(RES, 'drawable/ic_launcher_foreground.xml'),
    vectorFile(vectorGroup(ADAPTIVE_SCALE, PRIMARY), 'Adaptive-icon foreground.'))
  // Themed icons (Android 13+) tint a single-colour layer with the system
  // palette, so this one must be flat black — the launcher supplies the colour.
  writeFileSync(join(RES, 'drawable/ic_launcher_monochrome.xml'),
    vectorFile(vectorGroup(ADAPTIVE_SCALE, '#FF000000'),
      'Themed-icon layer. Flat black on purpose: the launcher recolours it.'))
  // The Android 12+ splash icon is masked like an adaptive icon too.
  writeFileSync(join(RES, 'drawable/ic_splash_icon.xml'),
    vectorFile(vectorGroup(ADAPTIVE_SCALE, PRIMARY), 'Android 12+ splash icon.'))

  const adaptive = kind => `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/gen-icons.mjs — do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`
  mkdirSync(join(RES, 'mipmap-anydpi-v26'), { recursive: true })
  writeFileSync(join(RES, 'mipmap-anydpi-v26/ic_launcher.xml'), adaptive())
  writeFileSync(join(RES, 'mipmap-anydpi-v26/ic_launcher_round.xml'), adaptive())

  for (const [density, px] of Object.entries(MIPMAP)) {
    const dir = join(RES, `mipmap-${density}`)
    mkdirSync(dir, { recursive: true })
    // Square and round both get the masked artwork: the round one is literally
    // circular, and the square one is what a pre-26 launcher may itself crop.
    const buf = await sharp(Buffer.from(maskableSvg(px))).png().toBuffer()
    writeFileSync(join(dir, 'ic_launcher.png'), buf)
    writeFileSync(join(dir, 'ic_launcher_round.png'), buf)
  }

  // Play Store listing icon — 512×512, 32-bit PNG, no transparency.
  mkdirSync(join(ROOT, '../store/assets'), { recursive: true })
  await sharp(Buffer.from(flatSvg(512))).png().toFile(join(ROOT, '../store/assets/icon-512.png'))

  // PWA / web build
  writeFileSync(join(ROOT, 'resources/icon.svg'), flatSvg(1024))
  await sharp(Buffer.from(flatSvg(1024))).png().toFile(join(ROOT, 'resources/icon.png'))
  await sharp(Buffer.from(flatSvg(180))).png().toFile(join(ROOT, 'public/icon-180.png'))
  await sharp(Buffer.from(flatSvg(512))).png().toFile(join(ROOT, 'public/icon-512.png'))
  await sharp(Buffer.from(maskableSvg(512))).png().toFile(join(ROOT, 'public/icon-maskable-512.png'))

  console.log('icons generated')
}

main().catch(e => { console.error(e); process.exit(1) })
